### ISSUE TITLE
Sveltekit error: <Doughnut> is not a valid SSR component

### ISSUE THREAD

**Issue by NikAgs** [SauravKanchan/svelte-chartjs#60]
I've tried adding chart.js svelte-chartjs as devDependencies and added this to my vite.config.js with no luck:
```
ssr: {
    noExternal: ['chart.js'],
}
```

Getting this stack trace: 

> Error: <Doughnut> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Module.validate_component (/node_modules/svelte/internal/index.mjs:1747:15)
    at eval (/src/routes/index.svelte:33:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.default (root.svelte:43:39)
    at eval (/src/routes/__layout.svelte:11:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at root.svelte:37:37
    at $$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1778:26)
    at render_response (file:///C:/Users/theni/Workspace/calica/calica-website/.svelte-kit/runtime/server/index.js:1461:27)

**Comment by dangreen** [comment]
@NikAgs Hi. svelte-chartjs doesn't support SSR.

**Comment by steddyman** [comment]
How do you make it render client side then if you are using sveltekit?

I have added it to a component with a regular <script> tag and I have added the following to vite.config.js and it still reports an SSR error:

	ssr: {
		noExternal: ['@carbon/charts', 'carbon-components', 'svelte-chartjs', 'chart.js'],
	}

This is the error it reports:
<Chart> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

**Comment by topazrn** [comment]
How should I disable SSR for certain pages then? I've tried putting `export const prerender = false;` in `+page.ts` according to the [docs](https://kit.svelte.dev/docs/routing#page-page-js) but it produces the same error.

**Comment by dangreen** [comment]
@NikAgs Hi. Please try https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v3.0.0
