### ISSUE TITLE
TypeError: block.l is not a function

### ISSUE THREAD

**Issue by guisousanunes** [SauravKanchan/svelte-chartjs#66]
Tried using svelte-chartjs in a blank svelte project by following:

```
npm create svelte@latest my-app
cd my-app
npm install
npm i svelte-chartjs chart.js
npm run dev -- --open
```

Created src/routes/+page.svelte:
```
<script>
import { Line } from 'svelte-chartjs'
import 'chart.js/auto';

const data = {...};
</script>

<Line {data}/>
```

First run: **_\<Line\> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules_**

Created src/hooks.js:
```
export const handle = async ({ event, resolve }) => {
	const response = await resolve(event, {
		ssr: false
	});
	return response;
};
```

Run:

```
Uncaught (in promise) TypeError: block.l is not a function
    at claim_component (index.mjs:1823:20)
    at Object.claim [as l] (+page.svelte:3:24)
    at claim_component (index.mjs:1823:20)
    at Object.claim [as l] (root.svelte? [sm]:47:55)
    at Object.claim [as l] (root.svelte? [sm]:42:20)
    at Object.claim [as l] (+layout.svelte? [sm]:13:81)
    at claim_component (index.mjs:1823:20)
    at Object.claim [as l] (root.svelte? [sm]:41:53)
    at Object.claim [as l] (root.svelte? [sm]:54:13)
    at init (index.mjs:1912:40)
```

**Comment by dangreen** [comment]
@guisousanunes Hi. Please try https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v3.0.0
