### ISSUE TITLE
[Bug]: Breaking imports when building to production with sveltkit.

### ISSUE THREAD

**Issue by PabloRuizCuevas** [SauravKanchan/svelte-chartjs#87]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

# current
In dev mode everything runs fine and the charts load correctly, but when trying to put it in a production environment running:

`npm run build 
`
we get the following error:
```

file:///home/pablo/webapp-seren/.svelte-kit/output/server/entries/pages/dashboard/_page.svelte.js:2
import { Chart as Chart$1, LineController, BarController, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, LineElement, PointElement } from "chart.js";
                                           ^^^^^^^^^^^^^
SyntaxError: Named export 'BarController' not found. The requested module 'chart.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'chart.js';
const { Chart: Chart$1, LineController, BarController, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, LineElement, PointElement } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async Module.component (file:///home/pablo/webapp-seren/.svelte-kit/output/server/nodes/4.js:4:39)
    at async Promise.all (index 1)
    at async render_response (file:///home/pablo/webapp-seren/.svelte-kit/output/server/index.js:1078:19)
    at async render_page (file:///home/pablo/webapp-seren/.svelte-kit/output/server/index.js:1543:12)
    at async resolve (file:///home/pablo/webapp-seren/.svelte-kit/output/server/index.js:2086:22)
    at async respond (file:///home/pablo/webapp-seren/.svelte-kit/output/server/index.js:2124:22)
file:///home/pablo/webapp-seren/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30
                                throw new Error(format(details));
```

#Expected

That npm run build works flawlessly.

### Reproduction

Just copied the bar example of this github and build it.

### chart.js version

v3.9.1

### svelte-chartjs version

v3.0.1

### Possible solution

I think this may be solved in v4 of charts js that was released two days ago, I saw that a bot committed the update of that version to github yesterday, but I'm not sure if it will work flawlessly because this version of charts.js introduces breaking changes.

**Comment by dangreen** [comment]
@PabloRuizCuevas Hi. Please try svelte-chartjs v3.1.0 and chart.js v4

**Comment by PabloRuizCuevas** [comment]
that works
